var jf = {};
jf.EventName = {};
jf.EventName.MM_XI_IN= "MM_XI_IN";
jf.EventName.MM_MEI_IN= "MM_MEI_IN";
jf.EventName.MM_WOLF_IN= "MM_WOLF_IN";
jf.EventName.MM_BUBTTON_IN= "MM_BUBTTON_IN";

jf.EventName.GP_UPDATE_SCORE_TEXT= "GP_UPDATE_SCORE_TEXT";
jf.EventName.GP_UPDATE_HP= "GP_UPDATE_HP";
jf.EventName.GP_ROLE_ATTACK_BEFORE= "GP_ROLE_ATTACK_BEFORE";
jf.EventName.GP_ROLE_ATTACK_AFTER= "GP_ROLE_ATTACK_AFTER";
