var jf = {};        // 定义自己的命名空间
jf.EventName = {};  // 事件名字对象
jf.EventName.MM_CREATE_GAMEPAD   = "MM_CREATE_GAMEPAD";
jf.EventName.MM_REMOVE_GAMEPAD   = "MM_REMOVE_GAMEPAD";
jf.EventName.MM_CREATE_GUIDE_LAYER   = "MM_CREATE_GUIDE_LAYER";
jf.EventName.MM_REMOVE_GUIDE_LAYER   = "MM_REMOVE_GUIDE_LAYER";
jf.EventName.MM_CREATE_RECORD_LAYER   = "MM_CREATE_RECORD_LAYER";
jf.EventName.MM_REMOVE_RECORD_LAYER   = "MM_REMOVE_RECORD_LAYER";

jf.EventName.GP_CREATE_GAMEPAD   = "GP_CREATE_GAMEPAD";
jf.EventName.GP_REMOVE_GAMEPAD   = "GP_REMOVE_GAMEPAD";
jf.EventName.GP_MENU_CREATE_GAMEPAD   = "GP_MENU_CREATE_GAMEPAD";
jf.EventName.GP_MENU_REMOVE_GAMEPAD   = "GP_MENU_REMOVE_GAMEPAD";
jf.EventName.GP_CREATE_MENU_LAYER   = "GP_CREATE_MENU_LAYER";
jf.EventName.GP_REMOVE_MENU_LAYER   = "GP_REMOVE_MENU_LAYER";
jf.EventName.GP_CREATE_LEVEL_LAYER   = "GP_CREATE_LEVEL_LAYER";
jf.EventName.GP_REMOVE_LEVEL_LAYER   = "GP_REMOVE_LEVEL_LAYER";
jf.EventName.GP_MONSTER_EAT_CARROT   = "GP_MONSTER_EAT_CARROT";
jf.EventName.GP_GAME_OVER   = "GP_GAME_OVER";
jf.EventName.GP_UPDATE_CARROT_BLOOD   = "GP_UPDATE_CARROT_BLOOD";
jf.EventName.GP_REMOVE_BULLET   = "GP_REMOVE_BULLET";
jf.EventName.GP_UPDATE_SCORE   = "GP_UPDATE_SCORE";
jf.EventName.GP_UPDATE_LEVEL   = "GP_UPDATE_LEVEL";

jf.EventName.GS_CREATE_RANKING_LAYER   = "GS_CREATE_RANKING_LAYER";
jf.EventName.GS_REMOVE_RANKING_LAYER   = "GS_REMOVE_RANKING_LAYER";
// 配置对象
var Config = {};
Config.IS_UP_UNLOCK_KEY = "is_up_unlock_key";

