var res = {
	// MainMenu
	mm_bg:"res/MainMenu/bg.jpg",
	mm_guide_1:"res/MainMenu/ts_1.png",
	mm_guide_2:"res/MainMenu/ts_2.png",
	mm_btn_1_1:"res/MainMenu/snav_1_1.png",
	mm_btn_1_2:"res/MainMenu/snav_1_2.png",
	mm_btn_2_1:"res/MainMenu/snav_2_1.png",
	mm_btn_2_2:"res/MainMenu/snav_2_2.png",
	mm_btn_3_1:"res/MainMenu/snav_3_1.png",
	mm_btn_3_2:"res/MainMenu/snav_3_2.png",
	mm_btn_xx_1:"res/MainMenu/xx_1.png",
	mm_btn_xx_2:"res/MainMenu/xx_2.png",
	mm_recode:"res/MainMenu/jl.png",

	gg_bg_1:"res/GamePlay/bg1.jpg",
	gg_bg_2:"res/GamePlay/bg2.png",
	gg_btn_pause_1:"res/GamePlay/zt.png",
	gg_btn_pause_2:"res/GamePlay/zt2.png",
	gg_btn_continue_1:"res/GamePlay/nav_1_1.png",
	gg_btn_continue_2:"res/GamePlay/nav_1_2.png",
	gg_btn_restart_1:"res/GamePlay/nav_2_1.png",
	gg_btn_restart_2:"res/GamePlay/nav_2_2.png",
	gg_btn_home_1:"res/GamePlay/nav_3_1.png",
	gg_btn_home_2:"res/GamePlay/nav_3_2.png",
	gg_plane_normal:"res/GamePlay/f.png",
	gg_fire_normal:"res/GamePlay/pd.png",
	gg_monster_1:"res/GamePlay/xs_1.png",
	gg_monster_2:"res/GamePlay/xs_2.png",
	gg_monster_3:"res/GamePlay/xs_3.png",
	gg_monster_4:"res/GamePlay/dj_1.png",
	gg_monster_5:"res/GamePlay/dj_2.png",
	gg_monster_bomb_1:"res/GamePlay/bz_1_1.png",
	gg_monster_bomb_2:"res/GamePlay/bz_1_2.png",
	gg_monster_bomb_3:"res/GamePlay/bz_1_3.png",
	gg_blood_3:"res/GamePlay/xt_4.png",
	gg_blood_2:"res/GamePlay/xt_3.png",
	gg_blood_1:"res/GamePlay/xt_2.png",
	gg_blood_bg:"res/GamePlay/xt_1.png",
	gg_score_bg:"res/GamePlay/jf.png",

	gs_bg:"res/GameResult/phb.png",
	gs_tip_1:"res/GameResult/zj.png",
	gs_tip_2:"res/GameResult/zj2.png",
	gs_btn_ranking_1:"res/GameResult/nav_4_1.png",
	gs_btn_ranking_2:"res/GameResult/nav_4_2.png",
	gs_r_1:"res/GameResult/jp_1.png",
	gs_r_2:"res/GameResult/jp_2.png",
	gs_r_3:"res/GameResult/jp_3.png",
	gs_r_4:"res/GameResult/s_1.png",
	gs_r_5:"res/GameResult/s_2.png",
	gs_r_6:"res/GameResult/s_3.png",
	gs_r_7:"res/GameResult/s_4.png",
	gs_r_8:"res/GameResult/s_5.png",
	gs_r_9:"res/GameResult/s_6.png",
	gs_r_10:"res/GameResult/s_7.png"
};
var g_resources = [];
for (var i in res) {
    g_resources.push(res[i]);
}